export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const BOOKMARK_EVENT = 'BOOKMARK_EVENT';
export const FIX_EVENT = 'FIX_EVENT';
export const REPLY_EVENT = 'REPLY_EVENT';
export const ADD_BOOKMARK_EVENT = 'ADD_BOOKMARK_EVENT'
export const DELETE_BOOKMARK_EVENT = 'DELETE_BOOKMARK_EVENT'